#!/bin/bash

docker=`which docker`

mysql_run() {
  sudo service mysqld "$@"
}

mysql_status() {
  mysql_run status "$@"
}

mysql_start() {
  mysql_run start "$@"
}

mysql_stop() {
  mysql_run stop "$@"
}

mysql_command() {
  cmd=$1
  shift
  case "$cmd" in
    "")
      mysql_run
      ;;
    status)
      mysql_status
      ;;
    start)
      mysql_start
      ;;
    stop)
      mysql_stop
      ;;
    *)
      echo_help
      ;;
  esac
}

HELP=`cat << EOF
$HELP
mysql(sudo):
  mysql status mysql status
  mysql start  mysql start
  mysql stop   mysql stop
  mysql        mysql run
EOF
`