#!/bin/bash

sudo_run() {
  command_run sudo "$@"
}

os_info() {
  echo_info uname -a
  echo ""

  # any os release files
  cat_if_exists "/etc/redhat-release"
  cat_if_exists "/etc/fedora-release"
  cat_if_exists "/etc/debian_version "
  cat_if_exists "/etc/lsb-release"
  cat_if_exists "/etc/turbolinux-release"
  cat_if_exists "/etc/SuSE-release"

  # proc version file
  cat_if_exists "/proc/version"
}

os_usingports() {
  sudo_run lsof -i "$@"
}

os_command() {
  cmd=$1
  shift
  case "$cmd" in
    info)
      os_info
      ;;
    usingports)
      os_usingports
      ;;
    *)
      echo_help
      ;;
  esac
}

HELP=`cat << EOF
$HELP
os:
  os info                           check os infomation
  os usingports(sudo)               check using ports(can specific ports :80,443)
EOF
`