#!/bin/bash

SSH_CONFIG=$HOME/.ssh/config

show_ssh_key_generate() {
  type="-t rsa"
  bit="-b 4096"
  comment="-C foo@bar.com"
  file="-f ~/.ssh/id_rsa"
  
  echo_info "ssh-keygen ${type} ${bit} ${comment} ${file}"
  echo ""
  echo "-C is comment. default format is {user@domain} it can delete if set \"\""
  echo ""

  echo "create public from secret"
  echo "ssh-keygen -y ${file} > ~/.ssh/id_rsa.pub"
  echo ""
}

show_ssh_config() {
  if [ ! -f "$SSH_CONFIG" ]; then
    echo "file not exists. $SSH_CONFIG"
    exit 0
  fi

  cat $SSH_CONFIG
}

show_ssh_config_hosts() {
  if [ ! -f "$SSH_CONFIG" ]; then
    echo "file not exists. $SSH_CONFIG"
    exit 0
  fi

  for i in `grep "^Host " $SSH_CONFIG | sed s/"^Host "// | grep -v "^\*$"`
  do
    echo "${i};"
  done
}

ssh_command() {
  cmd=$1
  shift
  case "$cmd" in
    key_generate)
      show_ssh_key_generate
      ;;
    config)
      show_ssh_config
      ;;
    config_hosts)
      show_ssh_config_hosts
      ;;
    *)
      echo_help
      ;;
  esac
}

HELP=`cat << EOF
$HELP
ssh:
  ssh config show   ssh config
  ssh config_hosts  show ssh config hosts
  ssh key_generate  show ssh key generate sample

EOF
`