#!/bin/bash

systemctl_run() {
  sudo_run systemctl "$@"
}

systemctl_status() {
  systemctl_run is-enabled "$@"
}

systemctl_start() {
  systemctl_run start "$@"
}

systemctl_stop() {
  systemctl_run stop "$@"
}

systemctl_autorun_start() {
  systemctl_run enable "$@"
}

systemctl_autorun_stop() {
  systemctl_run disable "$@"
}

HELP=`cat << EOF
$HELP
ssytemctl: for redhat os
  systemctl status {daemon}         systemctl status
  systemctl start {daemon}          systemctl start
  systemctl stop {daemon}           systemctl stop
  systemctl autorun_start {daemon}  systemctl autorun start
  systemctl autorun_stop {daemon}   systemctl autorun stop
EOF
`

systemctl_command() {
  cmd=$1
  shift
  case "$cmd" in
    status)
      systemctl_status "$@"
      ;;
    start)
      systemctl_start "$@"
      ;;
    stop)
      systemctl_stop "$@"
      ;;
    autorun_start)
      systemctl_autorun_start "$@"
      ;;
    autorun_stop)
      systemctl_autorun_stop "$@"
      ;;
    *)
      echo_help
      ;;
  esac
}